apiVersion: v1
kind: Pod
metadata:
  name: test-runner
spec:
  containers:
    - name: test
      image: avance-proyecto-computo-distribuido:test
      command: ["go", "test", "./server_test.go"]
  restartPolicy: Never